
package introsde.project.storage.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StorageImplService", targetNamespace = "http://soap.storage.project.introsde/", wsdlLocation = "http://storage-introsde-2018.herokuapp.com/ws/storage?wsdl")
public class StorageImplService
    extends Service
{

    private final static URL STORAGEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STORAGEIMPLSERVICE_EXCEPTION;
    private final static QName STORAGEIMPLSERVICE_QNAME = new QName("http://soap.storage.project.introsde/", "StorageImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://storage-introsde-2018.herokuapp.com/ws/storage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGEIMPLSERVICE_WSDL_LOCATION = url;
        STORAGEIMPLSERVICE_EXCEPTION = e;
    }

    public StorageImplService() {
        super(__getWsdlLocation(), STORAGEIMPLSERVICE_QNAME);
    }

    public StorageImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGEIMPLSERVICE_QNAME, features);
    }

    public StorageImplService(URL wsdlLocation) {
        super(wsdlLocation, STORAGEIMPLSERVICE_QNAME);
    }

    public StorageImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGEIMPLSERVICE_QNAME, features);
    }

    public StorageImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StorageInterface
     */
    @WebEndpoint(name = "StorageImplPort")
    public StorageInterface getStorageImplPort() {
        return super.getPort(new QName("http://soap.storage.project.introsde/", "StorageImplPort"), StorageInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StorageInterface
     */
    @WebEndpoint(name = "StorageImplPort")
    public StorageInterface getStorageImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.storage.project.introsde/", "StorageImplPort"), StorageInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGEIMPLSERVICE_EXCEPTION!= null) {
            throw STORAGEIMPLSERVICE_EXCEPTION;
        }
        return STORAGEIMPLSERVICE_WSDL_LOCATION;
    }

}
